### ISSUE TITLE
[BUG] App crashes instead of working

### ISSUE THREAD

**Issue by HarriBuh** [umutcamliyurt/MockTraffic#7]
``
[Device Brand]: google
[Device Model]: Pixel 7
[Android Version]: 14
[Android API Level]: 34
[Process ID]: 23684
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.nemesis.mocktraffic
[Version Name]: 1.0
[Version Code]: 1
[Target SDK]: 34
[Min SDK]: 24
[Error Type]: JVM
[Crash Time]: 2024-10-18T14:11:51.329
[Stack Trace]:
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but was 'mailto'
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1357)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1744)
	at okhttp3.Request$Builder.url(Request.kt:222)
	at com.nemesis.mocktraffic.TrafficService.makeHttpRequest(TrafficService.java:184)
	at com.nemesis.mocktraffic.TrafficService.access$300(TrafficService.java:39)
	at com.nemesis.mocktraffic.TrafficService$1.run(TrafficService.java:169)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)``

**Comment by umutcamliyurt** [comment]
Alr i will check it when i have time thanks for the detailed explanation

**Comment by umutcamliyurt** [comment]
It should be fixed right now
